package com.agendoc.security.jwt;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration properties used to issue and validate JWT access tokens.
 *
 * @param issuer issuer expected in tokens generated by AgenDoc
 * @param secret secret used to sign and validate tokens
 * @param expirationSeconds access token lifetime expressed in seconds
 */
@ConfigurationProperties(prefix = "agendoc.security.jwt")
public record JwtProperties(
        String issuer,
        String secret,
        long expirationSeconds
) {

    private static final int MINIMUM_SECRET_LENGTH = 32;

    public JwtProperties {
        if (issuer == null || issuer.isBlank()) {
            throw new IllegalArgumentException(
                    "JWT issuer must be configured"
            );
        }

        if (secret == null || secret.isBlank()) {
            throw new IllegalArgumentException(
                    "JWT secret must be configured"
            );
        }

        if (secret.length() < MINIMUM_SECRET_LENGTH) {
            throw new IllegalArgumentException(
                    "JWT secret must contain at least "
                            + MINIMUM_SECRET_LENGTH
                            + " characters"
            );
        }

        if (expirationSeconds <= 0) {
            throw new IllegalArgumentException(
                    "JWT expiration must be greater than zero"
            );
        }
    }
}