agendoc:
  security:
  cors:
    allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://192.168.68.104:5173

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/agendoc
    username: jc.castroc
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true